### ISSUE TITLE
Issues with toolkit github page

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.json#100]
1. There is a broken link on this page: https://ibmstreams.github.io/streamsx.json/docs/knowledge/overview/. The "Overview/use case" section goes to a 404.
2. The SPLDoc is using the 1.2.1 SPLDoc which is not the latest. This makes it hard to find documentation for the new functions

**Comment by rnostream** [comment]
The knowledge section has no sub-pages so far. So the overview navigation in side panel just refers now to itself.

There were two different version for SPLDOC for the toolkit available via different links from toolkits web-page. One which is just only the toolkit and one which is included in the samples SPLDOC. This needs to be separated later. For now samples SPLDOC was new generated and copied to gh-pages.

However SPLDOC still contains version 1.4.3. There are some issues to be discussed related to the release handling before updating to 1.4.4 (there are no functional changes from users perspective).
