### ISSUE TITLE
How to use the new functions for parsing JSON?

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/streamsx.json#101]
Please clarify the doc to explain the following:
- when to use the `extractJSON` function and when to the `parseJSON`/`queryJSON`functions.  Seems like you use the latter when you want to extract a specific attribute.  However, I do not understand the purpose of the `JsonIndex` enum, and it is not explained in the documentation.

**Comment by rnostream** [comment]
Just doing a clean up of issue list.

Its really hidden but it is available in the types.spl section of com.ibm.streams.json toolkit documentation. It's just an index to reference different parsed JSON strings held in memory to acces those on different places in code w/o reparsing.
