### ISSUE TITLE
javac: invalid target release: 1.8

### ISSUE THREAD

**Issue by xavrr** [IBMStreams/streamsx.json#113]
Running into troubles when trying to run ant in toolkit directory....

**Comment by rnostream** [comment]
I actually put the master to latest release 1.5.1 which requires IBM Streams 4.3. This was missed so far.
If you want the toolkit for a Streams version < 4.3 you need to checkout the maintenance branch 1.4.x_m.
The toolkit is build with Java 8 which is also contained in the IBM Streams installation directory.
Please check your environment settings for JAVA.
e.g.
source /home/streamsowner/InfoSphere_Streams/4.3.0.0/bin/streamsprofile.sh
#if you use the Java in Streams installation and not the system one
export JAVA_HOME=$STREAMS_INSTALL/java
export PATH=$JAVA_HOME/bin:$PATH

**Comment by rnostream** [comment]
Solution given. Code kept as is.
