### ISSUE TITLE
JSONToTuple generates empty tuples

### ISSUE THREAD

**Issue by AdiBg** [IBMStreams/streamsx.json#27]
Why?
also tried with jsonString as the stream attribute.

**Comment by rohitsw** [comment]
Please provide details. What input is being provided to the operator?

**Comment by AdiBg** [comment]
(stream<rstring X> inputStream) as JMSSource_1 = JMSSource()
		{
			param
				access : "vcAccess" ;
				connection : "vcConn" ;
		}

		(stream<vcin X> JSONToTuple_2_out0) as JSONToTuple_2 =
			JSONToTuple(inputStream)
		{
			param
				jsonStringAttribute:"X";
		}

**Comment by AdiBg** [comment]
ok got it. he wanted an extended schema.
