### ISSUE TITLE
Nominate Kirsten Hildurm (@hildrum) as commiter

### ISSUE THREAD

**Issue by rohitsw** [IBMStreams/streamsx.json#31]
Kris is familiar with the toolkit code and has contributes to features of the operators.

**Comment by chanskw** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by ddebrunner** [comment]
+1 but really for Kris's activity on IBMStreams in general. There is only a single pull request by Kris, so if that's the sole criteria for becoming a committer we are setting the bar very low.

**Comment by hildrum** [comment]
@ddebrunner -- some context, @rohitsw probably won't be contributing much if at all to IBMStreams after this Friday, and he's the sole committer here, so we figured we should have at least one active committer to replace him.

**Comment by chanskw** [comment]
@ddebrunner -- to clarify the requirement to become a committer.  For anyone to become a committer, the person must have contributed to the project and demonstrated that they have good understanding of the project code.  They also must have a good track record in the community.

For Kris, I have looked at her contribution on this project, and her track record on IBMStreams.  I believe she has a good understanding of the project and the code.  Therefore I support Kris to become a committer on the project.

**Comment by chanskw** [comment]
Closing.  Kris has been added as a committer.
