### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.json#32]

**Comment by hildrum** [comment]
I'd create a release if I were a committer.

**Comment by chanskw** [comment]
I will close the vote and finish the process next week.

**Comment by hildrum** [comment]
@chanskw When you do, could you also add a link to the documentation (http://ibmstreams.github.io/streamsx.json/)  in the description, that is, here: 
<img width="468" alt="screen shot 2015-07-17 at 1 08 55 am" src="https://cloud.githubusercontent.com/assets/5419652/8740998/70d13d98-2c20-11e5-947f-f8d9dfe69de0.png">

**Comment by hildrum** [comment]
Thanks @chanskw !

Release created: https://github.com/IBMStreams/streamsx.json/releases so closing.

**Comment by ddebrunner** [comment]
Thanks for the release!
