### ISSUE TITLE
Look at optimizing tracing in the operators.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.json#40]
In looking at JSONToTuple it seems there is a lot of tracing, while they are protected with checks of the tracing level, it looks like there are two checks per atttribute when doing the conversion.

It may be that the tracing was useful during initial development, but maybe they no longer provide any value.

**Comment by rnostream** [comment]
To check if this is actual still valid.

**Comment by markheger** [comment]
not valid anymore
traces with different levels in Java sources are fine.
debug traces are protected with checks of the tracing level
