### ISSUE TITLE
Operators need to handle mapping to SPL reserved keywords

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.json#72]
If a JSON document contains keys that are reserved words in SPL, there is currently no way to map those key/value pairs into an SPL attribute.

For example, suppose I have the following JSON: 

        {"type" : "a", "class" : "b"}

Since "type" and "class" are reserved words in SPL, you cannot have a schema that contains attributes with those names (i.e. tuple<rstring type, rstring class> is not valid).

The operators need to either handle the mapping of reserved key names (i.e. automatically map key "type" to something such as SPL attribute "type_") or allow the user to provide a custom mapping.

**Comment by markheger** [comment]
Operators should handle this similar to the XML parse operator with the [ignorePrefix](https://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$spl/op$spl.XML$XMLParse.html#spldoc_operator__parameter__ignorePrefix) parameter

**Comment by schulz2** [comment]
Closing after merge of Mark's changes.
