### ISSUE TITLE
Add support for auto conversion of numeric values to strings

### ISSUE THREAD

**Issue by erelsibm** [IBMStreams/streamsx.json#83]
currently if the user wants to parse a numeric value as string, it is not possible with the current function. this is important for the streaming pipelines use case where the user can define a schema and the system does the casting where possible behind the scenes. the same would apply to boolean values.

**Comment by ddebrunner** [comment]
Can you be more specific about the context you are talking about, or specifically what you are trying to do?

**Comment by erelsibm** [comment]
users might want to convert numbers to strings for various reasons, the issue is that if a user has set the field type to be a string in the edit schema widget in streaming pipelines, we will try to parse the field as string, currently what happens when it's a number in the json, it returns an empty string. the desired behavior is to auto convert the number to string representation of the number, same for boolean.

**Comment by ddebrunner** [comment]
Sorry, I meant using what operator/function.

**Comment by leongor** [comment]
@ddebrunner Lately, I have added native functions (parseJSON, queryJSON) to parse JSON. There is a support to implicitly convert string values to booleans and numbers to handle sloppy JSONs (when everything arrives as strings).
This issue is about the opposite case, when strings expected, bbut JSON values arrive without quotes.

**Comment by bmel** [comment]
@ddebrunner 
#### Real-world examples
Social security numbers or zip codes that a pipeline expects to be strings may occur in incoming JSON messages without quotes.

#### API Background
With the JSON parsing/query API, the type of requested values must be indicated, by way of a default value: "", 0.0, false, ...

#### Problem
For the examples above, requested values are not returned (or rather: the default empty string is returned) when requesting a value as string, and it is not quoted in JSON (such as SSNs or ZIP codes).

#### Suggested solution
When the requested value type is string and the actual value is not quoted (number, boolean), then the API should internally cast the value and return it as string.

**Comment by leongor** [comment]
I have a fix for this issue, but I don't want to merge it with the currently open PR: https://github.com/IBMStreams/streamsx.json/pull/85
Once it's merged I'll open a new PR for it.

**Comment by leongor** [comment]
PR opened: https://github.com/IBMStreams/streamsx.json/pull/88

**Comment by leongor** [comment]
Merged - can be closed.

**Comment by rnostream** [comment]
#88 merged
