### ISSUE TITLE
Float number corruption in JSON parsing

### ISSUE THREAD

**Issue by bmel** [IBMStreams/streamsx.json#90]
Apparently, due to inadvertently converting between 32-bit and 64-bit-precision floating types, rounding errors are visible immediately after parsing. For example, 1.1 turns into 1.10000002384186

**Comment by leongor** [comment]
Fixed as part of https://github.com/IBMStreams/streamsx.json/pull/88
Can be closed.

**Comment by rnostream** [comment]
#88 merged
