### ISSUE TITLE
Parse numbers into 'decimal' types

### ISSUE THREAD

**Issue by bmel** [IBMStreams/streamsx.json#92]
Currently, in terms of extracting numbers from JSON, only `int` and `float` types are supported. 
When I need to extract numbers from JSON into `decimal` types without precision loss, I need to work around by requesting the number value as a string and then casting it to value of a decimal type. In order to not cause a cast exception, I need to first try and extract the value as a `float`. This clutters my code and requires me to call queryJSON() twice, as in this example:
```
outTuple.lat = queryJSON("/lat", 0.0, status, JsonIndex._1);
if (outTuple.lat != 0.0) { 
    outTuple.lat = (decimal64) queryJSON("/lat", "", status, JsonIndex._1); 
}
```

Instead, I would like to be able to replace all this by simply calling:
```
outTuple.lat = queryJSON("/lat", 0.0d, status, JsonIndex._1); 
```

**Comment by leongor** [comment]
Fixed as part of this PR: https://github.com/IBMStreams/streamsx.json/pull/91

**Comment by rnostream** [comment]
#91 merged
