### ISSUE TITLE
queryJSON() returns wrong status for missing numeric values

### ISSUE THREAD

**Issue by bmel** [IBMStreams/streamsx.json#93]
### Problem
This example sets 'status' to FOUND_WRONG_TYPE instead of NOT_FOUND:
JSON: `{ "id":"a1" }`
API call: `myFloat64 = queryJSON("/name", 0.0, status, JsonIndex._1);`

**Comment by leongor** [comment]
Fixed as part of this PR: #91

**Comment by rnostream** [comment]
#91 Merged
